-- Tạo bảng lưu hình ảnh chi tiết cho sản phẩm theo GROUPSP (tiếng Việt)
CREATE TABLE IF NOT EXISTS hinhanh_sanpham (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  GROUPSP VARCHAR(20) NOT NULL,
  TENFILE VARCHAR(255) NOT NULL,
  THUTU INT DEFAULT 0,
  NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_groupsp (GROUPSP)
);
